TILE_SIZE = 32
GRID_COLS = 48
GRID_ROWS = 32

SCREEN_WIDTH = 1536
SCREEN_HEIGHT = 1024
WINDOW_WIDTH = 1408
WINDOW_HEIGHT = 736

FPS = 60
GAME_TITLE = "Super Delivery Game"

ALGORITHM_BFS = "BFS"
ALGORITHM_ASTAR = "ASTAR"
ALGORITHM_BEAM = "BEAM"
ALGORITHM_PARTIAL = "PARTIAL_OBSERVATION"
ALGORITHM_Q_LEARNING = "Q_LEARNING"

ALGORITHMS = [
    ALGORITHM_BFS,
    ALGORITHM_ASTAR,
    ALGORITHM_BEAM,
    ALGORITHM_PARTIAL,
    ALGORITHM_Q_LEARNING,
]

DEFAULT_ALGORITHM = ALGORITHM_ASTAR
DEFAULT_MAP_ID = 1

TILE_ROAD = 0
TILE_BLOCK = 1
TILE_STORE = 2
TILE_HOUSE = 3
TILE_TRAP = 4
TILE_WATER = 5
TILE_BRIDGE = 6
TILE_ROUNDABOUT = 7

WALKABLE_TILES = {
    TILE_ROAD,
    TILE_STORE,
    TILE_HOUSE,
    TILE_TRAP,
    TILE_BRIDGE,
    TILE_ROUNDABOUT,
}

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (220, 60, 60)
GREEN = (60, 180, 90)
BLUE = (70, 130, 220)
YELLOW = (240, 200, 60)
PURPLE = (160, 110, 220)

BACKGROUND_COLOR = (28, 32, 40)
GRID_LINE_COLOR = (70, 74, 84)
HUD_BG_COLOR = (18, 22, 30)
TEXT_COLOR = WHITE
PLAYER_COLOR = BLUE
NPC_COLORS = [RED, GREEN, YELLOW, PURPLE]

TARGET_REVENUE = 500

GRID_WIDTH = 48

GRID_HEIGHT = 32
